certificates:
  issuers:
    local:
      spec:
        ca: null
        vault:
          server: http://vault.default
          path: pki/sign/example-dot-com
          auth:
            kubernetes:
              mountPath: /v1/auth/kubernetes
              role: issuer
              secretRef:
                name: issuer-token-xm72k
                key: token
