{{- define "hpcc.issuers" -}}
apiVersion: cert-manager.io/v1
kind: {{ .me.kind | default "Issuer" }}
metadata:
  name: {{ .me.name }}
  namespace: {{ .root.Release.Namespace | default "default" }}
   {{- if .me.spec }}
spec:
{{ toYaml .me.spec | indent 2 }}
 {{- end }}
{{- end }}

{{- if $.Values.certificates -}}
 {{- if $.Values.certificates.enabled -}}
  {{- range $k, $v := .Values.certificates.issuers }}
{{- include "hpcc.issuers" (dict "root" $ "me" $v ) }}
---
  {{ end }}
 {{ end }}
{{ end }}
