##############################################################################
#
#    HPCC SYSTEMS software Copyright (C) 2020 HPCC Systems®.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
##############################################################################

# A version of the platform-core Dockerfile that keeps all the build artefacts in place, for use by developers wanting to debug the platform

FROM hpccsystems/platform-core:f6c217cb16-Debug-dirty-c48028e36ddb6abcb0f96122c5e65fa2

ADD multi-binding.xml /opt/HPCCSystems/bindings/multi-binding.xml
